### ISSUE TITLE
OpenPonk - crashes (Segmentation fault) when trying start OntUML UFO-A Editor

### ISSUE THREAD

**Issue by MichalNValenta** [OpenPonk/class-editor#11]
My system is:
Linux archlinux 5.8.13-arch1-1 #1 SMP PREEMPT Thu, 01 Oct 2020 20:40:35 +0000 x86_64 GNU/Linux

environment Cinnamon

additional hint: 
in order tu run the image, it was necessary to add LD_LIBRARY_PATH shell variable pointing to forlder with libraries 
libcurl-gnutls.so.4 and libnettle.so.6 

The complete report about the crash desplayd in shell is attached
[crash-report-09-10-2020.log](https://github.com/OpenPonk/class-editor/files/5353967/crash-report-09-10-2020.log)

Thanks
Michal

**Comment by JanBliznicenko** [comment]
Hello,

unfortunately, many linux distributions are not supported by Pharo and therefore OpenPonk. Known ones (to not work) are Fedora and OpenSUSE. Archlinux is not tested, but this seems to be the same library compatibility problem as with Fedora and OpenSUSE. Pointing to libcurl-gnutls might work, but any network related features of Pharo could cause crashes.
There is no known permanent fix, but unless student tries unrelated tools of Pharo itself, OpenPonk should work. Distributions that are known to work are based on Ubuntu or Debian, including Mint and some others.

Best regards,
Jan

**Comment by MichalNValenta** [comment]
Well, yesterday I was informed there is a new version published. It works fine now. I have to add that a successful attempt happened on LTS archlinux, I didn't remember if I tested the previous version on LTS.
