### ISSUE TITLE
openPonk crashes on MS Windows

### ISSUE THREAD

**Issue by MichalNValenta** [OpenPonk/class-editor#12]
My student tried to use OpenPonk with OntoUML UFO-A editor. Download the MS Win image and reported crash of OpenPonk on MS Win.

File is attached. Probably something related with UTF8...

Thanks for advice. 

Michal
![OpenPonk_startup_error](https://user-images.githubusercontent.com/38068729/95568918-2114a180-0a25-11eb-84fc-36807012e646.png)

**Comment by JanBliznicenko** [comment]
Hello, 

please ask the student to try latest/nightly build instead of 1.0.0, which is now quite outdated. UTF related problems should be fixed in latest build.

Jan

**Comment by JanBliznicenko** [comment]
Closing the issue for not applying to current version or build. If it does, please, reopen the issue.
