### ISSUE TITLE
Loading in Pharo 9 causes problems with PragmaMenuBuilder

### ISSUE THREAD

**Issue by hernanmd** [OpenPonk/class-editor#25]
Loading class-editor in Pharo 9 with the following script:

```smalltalk
EpMonitor disableDuring: [ 
	Metacello new
		onConflictUseLoaded;
		onWarningLog;
		baseline: 'ClassEditor';
		repository: 'github://OpenPonk/class-editor/repository';
		load: 'complete' ].
```

and opening a UML Class Diagram Editor -> Simple Association, gives the following error:

```bash
Original error: AssertionFailure: Pragma Collector cannot be changed..
Debugger error: OCUndeclaredVariableWarning: Undeclared temp: pragmaCollector
```

**Comment by JanBliznicenko** [comment]
Hello, unfortunately, OpenPonk does not yet support Pharo 9. There are multiple issues to be addressed, pragma usage rework is one of them.

**Comment by JanBliznicenko** [comment]
Current nightly build from master solves the issue. Versioned release during next week.
