### ISSUE TITLE
Is libgit external dependency?

### ISSUE THREAD

**Issue by MarekSuchanek** [OpenPonk/class-editor#29]
What are the requirements to run this thing on Windows? It seems that it requires some additional libraries...

![image](https://user-images.githubusercontent.com/9638527/135401496-7e0bdb8f-9137-4ff3-9a76-4a62c4eb7c49.png)

(v3.0.1)

**Comment by JanBliznicenko** [comment]
Problem comes from Pharo (language used by OP) VM that apparently cannot read anything from Windows network drives. OP is being executed from \msad-fs.ms.cvut\home... (as shown in window title), therefore many libraries and other dependencies did not load properly, including libgit dll, that is included in the OP directory.
I created issue on Pharo project: https://github.com/pharo-project/pharo/issues/10085, but I do not expect this issue to be fixed anytime soon. I recommend moving OP to C drive or flash drive or using it from own laptop.
