### ISSUE TITLE
Project gets broken after deleting enumeration

### ISSUE THREAD

**Issue by vlcekmat** [OpenPonk/class-editor#48]
Steps to reproduce:

1. Create Kind / Role entity
2. Create Enumeration entity
3. Create an association between the two entities
4. Delete enumeration entity

Probably caused: project cannot be saved, UI got broken
![issue1](https://github.com/OpenPonk/class-editor/assets/28135425/6ae6b0a0-87e5-46d0-9b1a-27f146c394a5)
![issue2](https://github.com/OpenPonk/class-editor/assets/28135425/b5a7c63c-1029-49b9-9259-ac37bc8d0ca4)
![Screenshot 2023-11-24 130637](https://github.com/OpenPonk/class-editor/assets/28135425/b9ec3261-e72c-4707-950b-f937965e30ff)

**Comment by JanBliznicenko** [comment]
Should be fixed in current nighly build
