### ISSUE TITLE
In Show / Hide Elements list show the associated classes

### ISSUE THREAD

**Issue by roper79** [OpenPonk/class-editor#55]
In the list, the other side of the generalisation (class name) is show. This should similarly work for associations, where currently just (Association) is shown. The name of the associated class should be shown, as well.

**Comment by JanBliznicenko** [comment]
Keep both name and nodes

**Comment by JanBliznicenko** [comment]
It shows the ends of associations along its name. Is it ok like this? If it is, please, close the issue.
